name: build 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/pld-linux/pld
    steps:    
    - name: pre
      run: poldek --noask --noprogress -Oparticle_install=no -u git-core libstdc++ fakeroot autoconf automake bzip2-devel check-devel docbook-dtd412-xml docbook2X gettext-tools libgomp-devel libtool libxml2-devel lua54-devel ncurses-devel openssl-devel pcre-devel perl-XML-Simple perl-base perl-modules pkgconfig popt-devel readline-devel rpm-devel tar texinfo xmlto xz zlib-devel zstd-devel
    - uses: actions/checkout@v4
    - name: configure
      run: ./autogen.sh && ./configure
    - name: make
      run: make CFLAGS="-O0"
    - name: make check 
      run: make check
    - name: make check-sh
      run: make check-sh
